permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Fern & Ivy"
  description: |
    A small online shop selling original digital illustrations.
  font_url: 'https://fonts.googleapis.com/css?family=Karla:400,400i,700,700i|Playfair+Display:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap'
